import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Map from "@/components/map";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mapbox_24_03_24</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map width="100vw" height="70vh"></Map>
      </main>
    </div>
  );
}
